### ISSUE TITLE
Update Docker Hub

### ISSUE THREAD

**Issue by bweston92** [shaunburdick/simple-smtp-server#1]
Just been wondering why SMTP authentication failed. I was under impression `_APPUSER` was the environment variable rather then `APP_USER`.

https://hub.docker.com/r/shaunburdick/simple-smtp-server/

**Comment by shaunburdick** [comment]
So, I'm bad at markdown. Github lets me do things like _SOME_VAR_ -> SOME_VAR but dockerhub does not. I'll update that.
